/* Purpose: Generates the website theme CSS variables from data/theme.json and optionally watches for changes. */

const fs = require("fs");
const path = require("path");

const themePath = path.join(__dirname, "../data/theme.json");
const outputPath = path.join(__dirname, "../assets/css/generated-theme.css");
const tailwindOutputPath = path.join(__dirname, "../assets/css/generated-theme.tailwind.css");
const DEFAULT_COLOR_GROUPS = ["theme_color", "text_color"];
const DEFAULT_FONT_FALLBACK = "sans-serif";
const WATCH_DEBOUNCE_MS = 300;

const toKebab = (str) => str.replace(/_/g, "-");
const findFont = (fontStr) => fontStr.replace(/\+/g, " ").replace(/:[^:]+/g, "");

function readThemeConfig() {
   if (!fs.existsSync(themePath)) {
      throw new Error(`Theme file not found: ${themePath}`);
   }

   const themeConfig = JSON.parse(fs.readFileSync(themePath, "utf8"));

   if (!themeConfig.colors || !themeConfig.fonts) {
      throw new Error("Invalid theme.json: missing 'colors' or 'fonts'");
   }

   return themeConfig;
}

function ensureOutputDirectory() {
   const outputDir = path.dirname(outputPath);
   if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
   }
}

function ensureDirectoryFor(filePath) {
   const outputDir = path.dirname(filePath);
   if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
   }
}

// Add color CSS variables with "clr-" prefix for clear Tailwind utility names
// e.g., --color-clr-primary → text-clr-primary, bg-clr-primary
function addColorsToCss(cssLines, colors, prefix = "") {
   Object.entries(colors).forEach(([key, value]) => {
      const colorName = prefix
         ? `--color-clr-${prefix}-${toKebab(key)}`
         : `--color-clr-${toKebab(key)}`;
      cssLines.push(`  ${colorName}: ${value};`);
   });
}

function addColorGroupsToCss(cssLines, groups, defaultGroups = []) {
   Object.entries(groups).forEach(([groupName, colors]) => {
      if (!colors || typeof colors !== "object") {
         return;
      }

      const prefix = defaultGroups.includes(groupName) ? "" : toKebab(groupName.replace(/_color$/, ""));
      addColorsToCss(cssLines, colors, prefix);
   });
}

function buildThemeVariableLines(themeConfig) {
   const cssLines = ["  /* === Colors === */"];

   if (themeConfig.colors.default) {
      addColorGroupsToCss(cssLines, themeConfig.colors.default, DEFAULT_COLOR_GROUPS);
   }

   if (themeConfig.colors.darkmode) {
      cssLines.push("", "  /* === Darkmode Colors === */");
      Object.entries(themeConfig.colors.darkmode).forEach(([groupName, colors]) => {
         if (!colors || typeof colors !== "object") {
            return;
         }

         const groupPrefix = DEFAULT_COLOR_GROUPS.includes(groupName)
            ? "darkmode"
            : `darkmode-${toKebab(groupName.replace(/_color$/, ""))}`;
         addColorsToCss(cssLines, colors, groupPrefix);
      });
   }

   cssLines.push("", "  /* === Font Families === */");
   const fontFamily = themeConfig.fonts.font_family || {};
   const fontFamilyTypes = themeConfig.fonts.font_family_type || {};
   Object.entries(fontFamily)
      .forEach(([key, font]) => {
         const fontFallback = fontFamilyTypes[key] || DEFAULT_FONT_FALLBACK;
         const fontValue = `${findFont(font)}, ${fontFallback}`;
         cssLines.push(`  --font-${toKebab(key)}: ${fontValue};`);
      });

   cssLines.push("", "  /* === Font Sizes === */");
   const baseSize = Number(themeConfig.fonts.font_size?.base || 16);
   const scaleSm = Number(themeConfig.fonts.font_size?.scale_sm || 0.9);

   cssLines.push(`  --text-size-base: ${baseSize}px;`);

   if (themeConfig.fonts.heading_sizes) {
      cssLines.push("", "  /* === Heading Size Variables === */");
      for (let i = 1; i <= 6; i++) {
         const size = themeConfig.fonts.heading_sizes[`h${i}`];
         if (size) {
            cssLines.push(`  --text-size-h${i}: ${size};`);
            const remMatch = size.match(/([\d.]+)rem/);
            if (remMatch) {
               const remValue = parseFloat(remMatch[1]);
               cssLines.push(`  --text-size-h${i}-sm: ${(remValue * scaleSm).toFixed(4)}rem;`);
            }
         }
      }
   }

   return cssLines;
}

function generateThemeCSS() {
   const themeConfig = readThemeConfig();

   const variableLines = buildThemeVariableLines(themeConfig);
   const cssLines = [
      "/**",
      ' * Auto-generated from "data/theme.json"',
      " * Purpose: Plain CSS custom properties for inspection and editor tooling.",
      " * This file is intentionally standard CSS so VS Code can treat it like a normal stylesheet.",
      " * DO NOT EDIT THIS FILE MANUALLY",
      " * Run: node scripts/themeGenerator.js",
      " */",
      "",
      ":root,",
      ":host {",
   ];

   cssLines.push(...variableLines);
   cssLines.push("}");

   const tailwindCssLines = [
      "/**",
      ' * Auto-generated from "data/theme.json" for Tailwind theme tokens',
      " * Purpose: Tailwind v4 @theme tokens consumed by the website theme entrypoint.",
      " * This file exists so Tailwind can compile theme utilities without forcing the plain token file to use @theme syntax.",
      " * DO NOT EDIT THIS FILE MANUALLY",
      " * Run: node scripts/themeGenerator.js",
      " */",
      "",
      "@theme {",
      ...variableLines,
      "}",
   ];

   ensureOutputDirectory();
   ensureDirectoryFor(tailwindOutputPath);
   fs.writeFileSync(outputPath, cssLines.join("\n") + "\n");
   fs.writeFileSync(tailwindOutputPath, tailwindCssLines.join("\n") + "\n");
   console.log("✅ Theme CSS generated:", outputPath);
   console.log("✅ Tailwind theme CSS generated:", tailwindOutputPath);
}

function runThemeGeneration({ exitOnError }) {
   try {
      generateThemeCSS();
   } catch (error) {
      console.error("❌ Error:", error.message);
      if (exitOnError) {
         process.exit(1);
      }
   }
}

runThemeGeneration({ exitOnError: true });

if (process.argv.includes("--watch")) {
   let debounceTimer;

   fs.watch(themePath, (eventType) => {
      if (eventType === "change") {
         clearTimeout(debounceTimer);
         debounceTimer = setTimeout(() => {
            runThemeGeneration({ exitOnError: false });
         }, WATCH_DEBOUNCE_MS);
      }
   });

   console.log("👁️  Watching:", themePath);
}
