const fs = require("fs");
const path = require("path");

// Simple project paths - no theme/exampleSite detection needed
const themePath = path.join(__dirname, "../data/theme.json");
const outputPath = path.join(__dirname, "../assets/css/generated-theme.css");

// Convert snake_case to kebab-case
const toKebab = (str) => str.replace(/_/g, "-");

// Extract font name (remove + and variants)
const findFont = (fontStr) => fontStr.replace(/\+/g, " ").replace(/:[^:]+/g, "");

// Add color CSS variables with "clr-" prefix for clear Tailwind utility names
// e.g., --color-clr-primary → text-clr-primary, bg-clr-primary
function addColorsToCss(cssLines, colors, prefix = "") {
   Object.entries(colors).forEach(([key, value]) => {
      const colorName = prefix
         ? `--color-clr-${prefix}-${toKebab(key)}`
         : `--color-clr-${toKebab(key)}`;
      cssLines.push(`  ${colorName}: ${value};`);
   });
}

function addColorGroupsToCss(cssLines, groups, defaultGroups = []) {
   Object.entries(groups).forEach(([groupName, colors]) => {
      if (!colors || typeof colors !== "object") {
         return;
      }

      const prefix = defaultGroups.includes(groupName) ? "" : toKebab(groupName.replace(/_color$/, ""));
      addColorsToCss(cssLines, colors, prefix);
   });
}

// Generate theme CSS from theme.json
function generateThemeCSS() {
   if (!fs.existsSync(themePath)) {
      throw new Error(`Theme file not found: ${themePath}`);
   }

   const themeConfig = JSON.parse(fs.readFileSync(themePath, "utf8"));

   if (!themeConfig.colors || !themeConfig.fonts) {
      throw new Error("Invalid theme.json: missing 'colors' or 'fonts'");
   }

   const cssLines = [
      "/**",
      ' * Auto-generated from "data/theme.json"',
      " * DO NOT EDIT THIS FILE MANUALLY",
      " * Run: node scripts/themeGenerator.js",
      " */",
      "",
      "@theme {",
      "  /* === Colors === */",
   ];

   // Default colors
   if (themeConfig.colors.default) {
      addColorGroupsToCss(cssLines, themeConfig.colors.default, ["theme_color", "text_color"]);
   }

   // Darkmode colors
   if (themeConfig.colors.darkmode) {
      cssLines.push("", "  /* === Darkmode Colors === */");
      Object.entries(themeConfig.colors.darkmode).forEach(([groupName, colors]) => {
         if (!colors || typeof colors !== "object") {
            return;
         }

         const groupPrefix = ["theme_color", "text_color"].includes(groupName)
            ? "darkmode"
            : `darkmode-${toKebab(groupName.replace(/_color$/, ""))}`;
         addColorsToCss(cssLines, colors, groupPrefix);
      });
   }

   // Font families
   cssLines.push("", "  /* === Font Families === */");
   const fontFamily = themeConfig.fonts.font_family || {};
   const fontFamilyTypes = themeConfig.fonts.font_family_type || {};
   Object.entries(fontFamily)
      .forEach(([key, font]) => {
         const fontFallback = fontFamilyTypes[key] || "sans-serif";
         const fontValue = `${findFont(font)}, ${fontFallback}`;
         cssLines.push(`  --font-${toKebab(key)}: ${fontValue};`);
      });

   // Font sizes
   cssLines.push("", "  /* === Font Sizes === */");
   const baseSize = Number(themeConfig.fonts.font_size?.base || 16);
   const scale_sm = Number(themeConfig.fonts.font_size?.scale_sm || 0.9);

   cssLines.push(`  --text-size-base: ${baseSize}px;`);
   cssLines.push(`  --text-size-base-sm: ${baseSize * scale_sm}px;`);

   // Heading size variables from theme.json
   if (themeConfig.fonts.heading_sizes) {
      cssLines.push("", "  /* === Heading Size Variables === */");
      for (let i = 1; i <= 6; i++) {
         const size = themeConfig.fonts.heading_sizes[`h${i}`];
         if (size) {
            cssLines.push(`  --text-size-h${i}: ${size};`);
            // Parse rem value and create -sm variant
            const remMatch = size.match(/([\d.]+)rem/);
            if (remMatch) {
               const remValue = parseFloat(remMatch[1]);
               cssLines.push(`  --text-size-h${i}-sm: ${(remValue * scale_sm).toFixed(4)}rem;`);
            }
         }
      }
   }

   cssLines.push("}");

   // Write the file
   const outputDir = path.dirname(outputPath);
   if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
   }

   fs.writeFileSync(outputPath, cssLines.join("\n") + "\n");
   console.log("✅ Theme CSS generated:", outputPath);
}

// Run on startup
try {
   generateThemeCSS();
} catch (error) {
   console.error("❌ Error:", error.message);
   process.exit(1);
}

// Watch mode
if (process.argv.includes("--watch")) {
   let debounceTimer;

   fs.watch(themePath, (eventType) => {
      if (eventType === "change") {
         clearTimeout(debounceTimer);
         debounceTimer = setTimeout(() => {
            try {
               generateThemeCSS();
            } catch (error) {
               console.error("❌ Error:", error.message);
            }
         }, 300);
      }
   });

   console.log("👁️  Watching:", themePath);
}
