export const MARKDOWN_VIEWER_CONTENT_AUTOFOCUS_DELAY_MS = 100;
export const MARKDOWN_VIEWER_RESTORE_FOCUS_DELAYS_MS = [0, 32, 96, 180] as const;
export const MARKDOWN_VIEWER_ENTER_EDIT_FOCUS_DELAYS_MS = [0, 16, 48] as const;
export const MARKDOWN_VIEWER_UNSAVED_DIALOG_RESTORE_FOCUS_DELAY_MS = 120;
export const MARKDOWN_EDITOR_AUTOFOCUS_RETRY_DELAYS_MS = [0, 25, 75, 150, 300] as const;
export const MARKDOWN_EDITOR_BASELINE_SYNC_WINDOW_MS = 200;
